In [47]:
# Final Project # 
# Stat 426 - Dr. Tass # 

import pandas as pd 
import numpy as np 
import re

In [15]:
# Read in the movie data from 2016-2019 and Add a year variable

table = pd.read_html("https://www.boxofficemojo.com/year/2019/?grossesOption=calendarGrosses")
movies = table[0]
movies['year'] = 2019
table = pd.read_html("https://www.boxofficemojo.com/year/2018/?grossesOption=calendarGrosses")
m2018 = table[0]
m2018['year'] = 2018
table = pd.read_html("https://www.boxofficemojo.com/year/2017/?grossesOption=calendarGrosses")
m2017 = table[0]
m2017['year'] = 2017
table = pd.read_html("https://www.boxofficemojo.com/year/2016/?grossesOption=calendarGrosses")
m2016 = table[0]
m2016['year'] = 2016
table = pd.read_html("https://www.boxofficemojo.com/year/2015/?grossesOption=calendarGrosses")
m2015 = table[0]
m2015['year'] = 2015
movies = pd.concat([movies, m2018, m2017, m2016, m2015], ignore_index = True)
# Remove empty columns 
movies.drop(columns = ['Genre', 'Budget', "Running Time", 'Estimated'], inplace = True)
movies.shape

(4456, 12)

In [23]:
movies.head()

,Rank,Release,Gross,Theaters,Total Gross,Release Date,Distributor,year
0,1,Avengers: Endgame,"$858,373,000",4662,"$858,373,000",Apr 26,Walt Disney Studios Motion Pictures,2019
1,2,The Lion King,"$543,638,043",4802,"$543,638,043",Jul 19,Walt Disney Studios Motion Pictures,2019
2,3,Toy Story 4,"$434,038,008",4575,"$434,038,008",Jun 21,Walt Disney Studios Motion Pictures,2019
3,4,Frozen II,"$430,144,682",4440,"$477,373,578",Nov 22,Walt Disney Studios Motion Pictures,2019
4,5,Captain Marvel,"$426,829,839",4310,"$426,829,839",Mar 8,Walt Disney Studios Motion Pictures,2019

In [119]:
# Read in data - downloaded from Kaggle https://www.kaggle.com/danielgrijalvas/movies
movies = pd.read_csv("/Users/camillahandley/Stat 426/Stat426FinalProject/Movies.csv")

# Only want US movies
movies = movies[movies['country'] == "USA"]
# Take out variables we don't need 
movies.drop(columns = ['runtime', 'score', 'votes', 'director', 'writer', 'country', 'star'], inplace = True)

In [120]:
# Parse out the Month and Day from 'released' variable
pattern = '\d+'
# assign False if there is not a full date and take out those observations 
movies = movies[movies['released'].apply(lambda x: True if len(re.findall(pattern, x)) == 3 else False)] 
movies['Day'] = movies['released'].apply(lambda x: int(re.findall(pattern, x)[2]))
movies['Month'] = movies['released'].apply(lambda x: int(re.findall(pattern, x)[1]))
# Remove extra columns 
movies.drop(columns = ['released'], inplace = True)

In [121]:
movies.head()

,budget,company,genre,gross,name,rating,year,Day,Month
0,8000000.0,Columbia Pictures Corporation,Adventure,52287414.0,Stand by Me,R,1986,22,8
1,6000000.0,Paramount Pictures,Comedy,70136369.0,Ferris Bueller's Day Off,PG-13,1986,11,6
2,15000000.0,Paramount Pictures,Action,179800601.0,Top Gun,PG,1986,16,5
3,18500000.0,Twentieth Century Fox Film Corporation,Action,85160248.0,Aliens,R,1986,18,7
4,9000000.0,Walt Disney Pictures,Adventure,18564613.0,Flight of the Navigator,PG,1986,1,8

In [96]:
# Figure out a way to add a holiday variable?? 
# Make a season variable 
# Make a dummy variable for rating and genre and Company